GET http://localhost:1337/api/
###
GET http://localhost:1337/api/fdsfsdfsddfsd
Content-Type: application/json

{
    "data":{
        "firstName": "Leonardo",
        "lastName": "Di carpaccio"
    }
}
###
GET http://localhost:1337/api/movies
###
GET https://api.themoviedb.org/3/search/movie?query=Jack+Reacher&api_key=c6a980d3de8f528a560e5f61c76ebedc
###
POST http://localhost:1337/api/movies
Content-Type: application/json

{
  "data":{
    "description": "When a gunman takes five lives with six shots, all evidence points to the suspect in custody. On interrogation, the suspect offers up a single note: \"Get Jack Reacher!\" So begins an extraordinary chase for the truth, pitting Jack Reacher against an unexpected enemy, with a skill for violence and a secret to keep.",
    "title": "Jack Reacher",
    "releaseDate": "2012-12-20",
    "director": "Jean Mich",
    "actors":[1]
  }
}

###
POST http://localhost:1337/api/movies
Content-Type: application/json

{
  "data":{
    "description": "When a gunman takes five lives with six shots, all evidence points to the suspect in custody. On interrogation, the suspect offers up a single note: \"Get Jack Reacher!\" So begins an extraordinary chase for the truth, pitting Jack Reacher against an unexpected enemy, with a skill for violence and a secret to keep.",
    "title": "Javk vj;jb",
    "releaseDate": "2012-12-20",
    "director": "Jean Mich",
    "actors":[1]
    } 
}
###
GET http://localhost:1337/api/actors
###

POST http://localhost:1337/api/actors
Content-Type: application/json

{
    "data":{
        "firstName": "Rosamund",
        "lastName": "Pike"
    }
}
###
PUT http://localhost:1337/api/actors/3
Content-Type: application/json

{
    "data":{
        "firstName": "Rosamund",
        "lastName": "Pike"
    }
}
###

PUT http://localhost:1337/api/movies/2
Content-Type: application/json

{
  "data":{
    "description": "When a gunman takes five lives with six shots, all evidence points to the suspect in custody. On interrogation, the suspect offers up a single note: \"Get Jack Reacher!\" So begins an extraordinary chase for the truth, pitting Jack Reacher against an unexpected enemy, with a skill for violence and a secret to keep.",
    "title": "Jack Reacher",
    "releaseDate": "2012-12-20",
    "director": "Jean Mich",
    "actors":[2]
    } 
}
###
GET http://localhost:1337/api/movies?populate=actors

###
GET http://localhost:1337/api/movies?filters[title][$startsWith]=J

###
PUT http://localhost:1337/api/actors/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiU29uR29rdSIsImlhdCI6MTcwMjM4MDU1NSwiZXhwIjoxNzAyMzg0MTU1fQ.dX3YiqY6AjcBH1ez46KwjSUiz9_DF4Zhlwg7CGsaSwA

{
    "data":{
        "firstName": "Leonardo",
        "lastName": "Di carpaccio"
    }
}
###
POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
    "login": "SsonGocdsqku",
    "password": "songokdu1235699"
}

###
POST http://localhost:1337/api/auth/local/register
Content-Type: application/json

{
    "login": "SsonGocdsqku",
    "password": "songokdu123"
}
###
DELETE  http://localhost:1337/api/actors/2

###
GET  http://localhost:1337/api/movies/2
###
POST http://localhost:1337/api/movies/

###
PUT http://localhost:1337/api/movies/

###
DELETE  http://localhost:1337/api/movies/1

###
GET http://localhost:1337/api/users/me

###
POST http://localhost:1337/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhVG9TaWduIjp7InVzZXJJZCI6MX0sImlhdCI6MTcwMjM5NTExNSwiZXhwIjoxNzAyMzk4NzE1fQ.vtxrlr1FnFHPxmpL6Shfbau8btz6H7QYQr-Cahgof_s

{
    "login": "SsonGocdsqku",
    "password": "songokdu1235699"
}

###
GET http://localhost:1337/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMjM4Nzg5MywiZXhwIjoxNzAyMzkxNDkzfQ.y0t96Wk_NbhoR-2nTE9SB-ZJusEwyU4KIULAKKL4guA
